# app1 alias
apiVersion: v1
kind: Service
metadata:
  name: app1-env1-alias
  namespace: default
spec:
  type: ExternalName
  externalName: app1-env1.env-1.svc.cluster.local
  ports:
    - port: 5001
      targetPort: 5001
---
# app2-env1 alias
apiVersion: v1
kind: Service
metadata:
  name: app2-env1-alias
  namespace: default
spec:
  type: ExternalName
  externalName: app2-env1.env-1.svc.cluster.local
  ports:
    - port: 5002
      targetPort: 5002
---
# app2-env2 alias
apiVersion: v1
kind: Service
metadata:
  name: app2-env2-alias
  namespace: default
spec:
  type: ExternalName
  externalName: app2-env2.env-2.svc.cluster.local
  ports:
    - port: 5002
      targetPort: 5002
---
# app3-env3 alias
apiVersion: v1
kind: Service
metadata:
  name: app3-env3-alias
  namespace: default
spec:
  type: ExternalName
  externalName: app3-env3.env-3.svc.cluster.local
  ports:
    - port: 5003
      targetPort: 5003
