apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-apps-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /log
spec:
  rules:
  - host: logservice.local
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-env1-alias
            port:
              number: 5001
      - path: /app2/env1
        pathType: Prefix
        backend:
          service:
            name: app2-env1-alias
            port:
              number: 5002
      - path: /app2/env2
        pathType: Prefix
        backend:
          service:
            name: app2-env2-alias
            port:
              number: 5002
      - path: /app3
        pathType: Prefix
        backend:
          service:
            name: app3-env3-alias
            port:
              number: 5003
